
name: Database Deployment

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install MySQL Connector
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python

    - name: Run SQL Scripts on Azure MySQL
      env:
        MYSQL_HOST: ${{ secrets.DB_HOST }}
        MYSQL_USER: ${{ secrets.DB_ADMIN_USER }}
        MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        MYSQL_DB: ${{ secrets.DB_NAME }}
      run: |
        python execute_sql_script.py

